# База задач для 3 и 6 классов (в стиле МЦКО)

QUESTIONS = {
    3: {
        "математика": [
            {"text": "Вычисли: 47 + 26", "answer": "73", "explanation": "47 + 26 = 73"},
            {"text": "Вычисли: 82 - 39", "answer": "43", "explanation": "82 - 39 = 43"},
            {"text": "Сколько будет 8 × 7?", "answer": "56", "explanation": "8 × 7 = 56"},
            {"text": "Раздели 54 на 6", "answer": "9", "explanation": "54 : 6 = 9"},
            {"text": "В классе 30 учеников, из них 12 девочек. Сколько мальчиков?", "answer": "18", "explanation": "30 - 12 = 18"},
            {"text": "Найди периметр квадрата со стороной 6 см", "answer": "24", "explanation": "6 × 4 = 24"},
            {"text": "Сколько минут в 3 часах?", "answer": "180", "explanation": "3 × 60 = 180"},
        ],
        "русский": [
            {"text": "В каком слове пропущена буква 'о'?\nА) тр..ва\nБ) м..ре\nВ) г..ра\nГ) сл..во", "answer": "Б", "explanation": "море"},
            {"text": "Найди существительное:\nА) бегать\nБ) бег\nВ) быстрый\nГ) быстро", "answer": "Б", "explanation": "бег — что?"},
            {"text": "Сколько гласных букв в русском языке?", "answer": "10", "explanation": "10"},
        ],
        "биология": [
            {"text": "Какое животное впадает в спячку?", "answer": "медведь", "explanation": "медведь"},
            {"text": "Что нужно растениям для роста?", "answer": "свет", "answer_alt": "солнце", "explanation": "свет"},
        ],
        "история": [
            {"text": "Столица России?", "answer": "Москва", "explanation": "Москва"},
            {"text": "Первый космонавт?", "answer": "Гагарин", "explanation": "Юрий Гагарин"},
        ],
    },

    6: {
        "математика": [
            {"text": "Вычисли: -7 + 9", "answer": "2", "explanation": "2"},
            {"text": "Вычисли: -12 - 5", "answer": "-17", "explanation": "-17"},
            {"text": "Найди модуль числа -25", "answer": "25", "explanation": "|-25|=25"},
            {"text": "Сравни: -3 ... 2", "answer": "<", "explanation": "-3 < 2"},
            {"text": "Вычисли: 1/2 + 3/4", "answer": "5/4", "answer_alt": "1,25", "explanation": "5/4"},
            {"text": "Вычисли: 0,6 × 5", "answer": "3", "explanation": "3"},
            {"text": "Найди 20% от 150", "answer": "30", "explanation": "150×0.2=30"},
            {"text": "Сколько целых в 19/4?", "answer": "4", "explanation": "4"},
            {"text": "Реши: 3x = 21", "answer": "7", "explanation": "x=7"},
            {"text": "НОК(4,6)", "answer": "12", "explanation": "12"},
            {"text": "Округли 5,678 до сотых", "answer": "5,68", "explanation": "5,68"},
            {"text": "Вычисли: 3² + 5²", "answer": "34", "explanation": "9+25"},
            {"text": "72 км/ч в м/с", "answer": "20", "explanation": "20"},
            {"text": "Площадь круга R=2 (π=3,14)", "answer": "12,56", "explanation": "3,14×4"},
            {"text": "Длина окружности R=3", "answer": "18,84", "explanation": "2πR"},
            {"text": "Вычисли: -6 - (-4)", "answer": "-2", "explanation": "-2"},
            {"text": "Вычисли: 10 - 3×(-2)", "answer": "16", "explanation": "10+6"},
            {"text": "Реши: 2x+3=11", "answer": "4", "explanation": "x=4"},
            {"text": "12 от 60 это сколько %?", "answer": "20", "explanation": "20%"},
            {"text": "180 км за 3 ч — скорость", "answer": "60", "explanation": "60"},
        ],

        "русский": [
            {"text": "Где НН?\nА) ветреный\nБ) стеклянный\nВ) юный\nГ) румяный", "answer": "Б", "explanation": "исключение"},
            {"text": "Деепричастие:\nА) бежал\nБ) бегая\nВ) бег\nГ) бегущий", "answer": "Б", "explanation": "бегая"},
            {"text": "Суффикс в слове 'учительница'", "answer": "ниц", "explanation": "ниц"},
            {"text": "Приставка рас-\nА) рассказ\nБ) распилить\nВ) растение\nГ) рост", "answer": "Б", "explanation": "рас-"},
            {"text": "Фразеологизм это", "answer": "устойчивое выражение", "explanation": ""},
            {"text": "Сколько склонений?", "answer": "3", "explanation": ""},
            {"text": "Разноспрягаемый глагол", "answer": "хотеть", "explanation": ""},
            {"text": "Слово с ъ\nА) вьюга\nБ) подъезд\nВ) семья\nГ) листья", "answer": "Б", "explanation": ""},
            {"text": "Чередование корня", "answer": "растение", "explanation": ""},
            {"text": "Падеж: по дороге", "answer": "дательный", "explanation": ""},
            {"text": "Союз", "answer": "и", "explanation": ""},
            {"text": "Падежей сколько?", "answer": "6", "explanation": ""},
            {"text": "Олицетворение это", "answer": "очеловечивание", "explanation": ""},
            {"text": "Слово с Е\nА) бл..стеть\nБ) зам..рать", "answer": "А", "explanation": ""},
            {"text": "Предлог раздельно", "answer": "в течение", "explanation": ""},
        ],

        "биология": [
            {"text": "Наука о растениях", "answer": "ботаника", "explanation": ""},
            {"text": "Подземная часть", "answer": "корень", "explanation": ""},
            {"text": "Травоядные — это", "answer": "едят растения", "explanation": ""},
            {"text": "Хищники — это", "answer": "едят мясо", "explanation": ""},
            {"text": "Орган мышления", "answer": "мозг", "explanation": ""},
            {"text": "Камер сердца", "answer": "4", "explanation": ""},
            {"text": "Газ фотосинтеза", "answer": "кислород", "explanation": ""},
            {"text": "Клетки иммунитета", "answer": "лейкоциты", "explanation": ""},
            {"text": "Костей у человека", "answer": "206", "explanation": ""},
            {"text": "Витамин солнца", "answer": "витамин D", "explanation": ""},
            {"text": "Самая большая железа", "answer": "печень", "explanation": ""},
            {"text": "Самое большое животное", "answer": "кит", "explanation": ""},
            {"text": "Гетеротрофы", "answer": "питаются готовым", "explanation": ""},
            {"text": "Орган зрения", "answer": "глаза", "explanation": ""},
            {"text": "Микроорганизмы болезни", "answer": "бактерии", "explanation": ""},
            {"text": "Процесс переваривания", "answer": "пищеварение", "explanation": ""},
            {"text": "Литров крови", "answer": "5", "explanation": ""},
            {"text": "Наука о клетках", "answer": "цитология", "explanation": ""},
        ],

        "история": [
            {"text": "Основатель Романовых", "answer": "Михаил Романов", "explanation": ""},
            {"text": "1812 год — что?", "answer": "война", "explanation": ""},
            {"text": "Командующий 1812", "answer": "Кутузов", "explanation": ""},
            {"text": "1242 событие", "answer": "Ледовое побоище", "explanation": ""},
            {"text": "Отмена крепостного права", "answer": "1861", "explanation": ""},
            {"text": "Последний царь", "answer": "Николай II", "explanation": ""},
            {"text": "Первая мировая", "answer": "1914", "explanation": ""},
            {"text": "Лидер революции", "answer": "Ленин", "explanation": ""},
            {"text": "Первый спутник", "answer": "1957", "explanation": ""},
            {"text": "Первый космонавт", "answer": "Гагарин", "explanation": ""},
            {"text": "Распад СССР", "answer": "1991", "explanation": ""},
            {"text": "Первый президент РФ", "answer": "Ельцин", "explanation": ""},
            {"text": "ВОВ годы", "answer": "1941-1945", "explanation": ""},
            {"text": "9 мая 1945", "answer": "Победа", "explanation": ""},
            {"text": "Берлин 1945", "answer": "Жуков", "explanation": ""},
            {"text": "Вторая мировая", "answer": "1939", "explanation": ""},
            {"text": "Корабль Гагарина", "answer": "Восток-1", "explanation": ""},
        ],
    },
}
